// Runtime DB initialization for Vercel serverless
// Creates SQLite DB + tables + seed data on first access

import { PrismaClient } from '@prisma/client'
import { existsSync, mkdirSync, writeFileSync, readFileSync } from 'fs'
import path from 'path'

let initialized = false

// The Prisma schema as SQL — generated by prisma migrate
// We embed the CREATE TABLE statements directly
const SCHEMA_SQL = `
CREATE TABLE IF NOT EXISTS User (
  id TEXT NOT NULL PRIMARY KEY,
  email TEXT NOT NULL,
  username TEXT NOT NULL,
  name TEXT NOT NULL,
  passwordHash TEXT,
  phone TEXT,
  avatar TEXT,
  bio TEXT NOT NULL DEFAULT '',
  gender TEXT NOT NULL DEFAULT 'other',
  dob TEXT,
  role TEXT NOT NULL DEFAULT 'user',
  isPremium BOOLEAN NOT NULL DEFAULT false,
  premiumUntil DATETIME,
  premiumTier TEXT NOT NULL DEFAULT 'free',
  isOnline BOOLEAN NOT NULL DEFAULT false,
  lastSeen DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  isRestricted BOOLEAN NOT NULL DEFAULT false,
  restrictedUntil DATETIME,
  isBlocked BOOLEAN NOT NULL DEFAULT false,
  blockedUntil DATETIME,
  banReason TEXT,
  authProvider TEXT NOT NULL DEFAULT 'email',
  referralCode TEXT,
  behaviorScore INTEGER NOT NULL DEFAULT 100,
  behaviorLogs TEXT NOT NULL DEFAULT '',
  adsWatchedToday INTEGER NOT NULL DEFAULT 0,
  lastAdWatchedAt DATETIME,
  twoFactorSecret TEXT,
  twoFactorEnabled BOOLEAN NOT NULL DEFAULT false,
  rewardLoop TEXT NOT NULL DEFAULT 'welcome',
  welcomeBonusClaimed BOOLEAN NOT NULL DEFAULT false,
  lastDeactivatedAt DATETIME,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS User_email_key ON User(email);
CREATE UNIQUE INDEX IF NOT EXISTS User_username_key ON User(username);
CREATE INDEX IF NOT EXISTS User_email_idx ON User(email);
CREATE INDEX IF NOT EXISTS User_username_idx ON User(username);
CREATE INDEX IF NOT EXISTS User_role_idx ON User(role);

CREATE TABLE IF NOT EXISTS Conversation (
  id TEXT NOT NULL PRIMARY KEY,
  type TEXT NOT NULL DEFAULT 'private',
  name TEXT,
  avatar TEXT,
  ownerId TEXT,
  groupId TEXT,
  wallpaper TEXT,
  muted BOOLEAN NOT NULL DEFAULT false,
  pinned BOOLEAN NOT NULL DEFAULT false,
  autoDeleteAfter INTEGER,
  themeColor TEXT,
  sentBubbleColor TEXT,
  receivedBubbleColor TEXT,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS Conversation_groupId_key ON Conversation(groupId);
CREATE INDEX IF NOT EXISTS Conversation_type_idx ON Conversation(type);
CREATE INDEX IF NOT EXISTS Conversation_groupId_idx ON Conversation(groupId);

CREATE TABLE IF NOT EXISTS ConversationMember (
  id TEXT NOT NULL PRIMARY KEY,
  conversationId TEXT NOT NULL,
  userId TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'member',
  lastReadAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  joinedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (conversationId) REFERENCES Conversation(id) ON DELETE CASCADE,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS ConversationMember_conversationId_userId_key ON ConversationMember(conversationId, userId);
CREATE INDEX IF NOT EXISTS ConversationMember_userId_idx ON ConversationMember(userId);

CREATE TABLE IF NOT EXISTS Message (
  id TEXT NOT NULL PRIMARY KEY,
  conversationId TEXT NOT NULL,
  senderId TEXT NOT NULL,
  content TEXT NOT NULL DEFAULT '',
  type TEXT NOT NULL DEFAULT 'text',
  mediaUrl TEXT,
  voiceDuration INTEGER,
  stickerId TEXT,
  replyToId TEXT,
  forwardedFromId TEXT,
  lat REAL,
  lng REAL,
  editedAt DATETIME,
  deletedAt DATETIME,
  pinnedAt DATETIME,
  seenBy TEXT NOT NULL DEFAULT '',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL,
  FOREIGN KEY (conversationId) REFERENCES Conversation(id) ON DELETE CASCADE,
  FOREIGN KEY (senderId) REFERENCES User(id),
  FOREIGN KEY (replyToId) REFERENCES Message(id),
  FOREIGN KEY (forwardedFromId) REFERENCES Message(id)
);
CREATE INDEX IF NOT EXISTS Message_conversationId_createdAt_idx ON Message(conversationId, createdAt);
CREATE INDEX IF NOT EXISTS Message_senderId_idx ON Message(senderId);

CREATE TABLE IF NOT EXISTS Reaction (
  id TEXT NOT NULL PRIMARY KEY,
  messageId TEXT NOT NULL,
  userId TEXT NOT NULL,
  emoji TEXT NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (messageId) REFERENCES Message(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS Reaction_messageId_userId_key ON Reaction(messageId, userId);
CREATE INDEX IF NOT EXISTS Reaction_messageId_idx ON Reaction(messageId);

CREATE TABLE IF NOT EXISTS Group (
  id TEXT NOT NULL PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  logo TEXT,
  category TEXT NOT NULL DEFAULT 'Other',
  isPublic BOOLEAN NOT NULL DEFAULT true,
  inviteCode TEXT NOT NULL,
  ownerId TEXT NOT NULL,
  creatorId TEXT,
  membersCount INTEGER NOT NULL DEFAULT 1,
  pinnedMessageIds TEXT NOT NULL DEFAULT '',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL,
  FOREIGN KEY (ownerId) REFERENCES User(id),
  FOREIGN KEY (creatorId) REFERENCES User(id)
);
CREATE UNIQUE INDEX IF NOT EXISTS Group_inviteCode_key ON Group(inviteCode);
CREATE INDEX IF NOT EXISTS Group_category_idx ON Group(category);
CREATE INDEX IF NOT EXISTS Group_isPublic_idx ON Group(isPublic);

CREATE TABLE IF NOT EXISTS GroupMember (
  id TEXT NOT NULL PRIMARY KEY,
  groupId TEXT NOT NULL,
  userId TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'member',
  joinedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (groupId) REFERENCES Group(id) ON DELETE CASCADE,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS GroupMember_groupId_userId_key ON GroupMember(groupId, userId);
CREATE INDEX IF NOT EXISTS GroupMember_groupId_idx ON GroupMember(groupId);
CREATE INDEX IF NOT EXISTS GroupMember_userId_idx ON GroupMember(userId);

CREATE TABLE IF NOT EXISTS Notification (
  id TEXT NOT NULL PRIMARY KEY,
  userId TEXT NOT NULL,
  type TEXT NOT NULL,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  data TEXT NOT NULL DEFAULT '{}',
  isRead BOOLEAN NOT NULL DEFAULT false,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS Notification_userId_isRead_idx ON Notification(userId, isRead);

CREATE TABLE IF NOT EXISTS Report (
  id TEXT NOT NULL PRIMARY KEY,
  reporterId TEXT NOT NULL,
  reportedUserId TEXT,
  reportedGroupId TEXT,
  reason TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'pending',
  adminNote TEXT,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL,
  FOREIGN KEY (reporterId) REFERENCES User(id),
  FOREIGN KEY (reportedUserId) REFERENCES User(id),
  FOREIGN KEY (reportedGroupId) REFERENCES Group(id)
);
CREATE INDEX IF NOT EXISTS Report_status_idx ON Report(status);
CREATE INDEX IF NOT EXISTS Report_reportedUserId_idx ON Report(reportedUserId);

CREATE TABLE IF NOT EXISTS Block (
  id TEXT NOT NULL PRIMARY KEY,
  blockerId TEXT NOT NULL,
  blockedId TEXT NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (blockerId) REFERENCES User(id) ON DELETE CASCADE,
  FOREIGN KEY (blockedId) REFERENCES User(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS Block_blockerId_blockedId_key ON Block(blockerId, blockedId);

CREATE TABLE IF NOT EXISTS Advertisement (
  id TEXT NOT NULL PRIMARY KEY,
  brandName TEXT NOT NULL,
  headline TEXT NOT NULL,
  description TEXT NOT NULL,
  imageUrl TEXT,
  ctaText TEXT NOT NULL DEFAULT 'Learn More',
  ctaUrl TEXT NOT NULL DEFAULT '#',
  placement TEXT NOT NULL DEFAULT 'in-chat',
  category TEXT,
  startDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  endDate DATETIME,
  isActive BOOLEAN NOT NULL DEFAULT true,
  impressions INTEGER NOT NULL DEFAULT 0,
  clicks INTEGER NOT NULL DEFAULT 0,
  creatorId TEXT,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL,
  FOREIGN KEY (creatorId) REFERENCES User(id)
);
CREATE INDEX IF NOT EXISTS Advertisement_placement_isActive_idx ON Advertisement(placement, isActive);

CREATE TABLE IF NOT EXISTS AdClick (
  id TEXT NOT NULL PRIMARY KEY,
  adId TEXT NOT NULL,
  userId TEXT NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (adId) REFERENCES Advertisement(id) ON DELETE CASCADE,
  FOREIGN KEY (userId) REFERENCES User(id)
);
CREATE INDEX IF NOT EXISTS AdClick_adId_idx ON AdClick(adId);

CREATE TABLE IF NOT EXISTS UserPreference (
  id TEXT NOT NULL PRIMARY KEY,
  userId TEXT NOT NULL,
  theme TEXT NOT NULL DEFAULT 'system',
  wallpaper TEXT NOT NULL DEFAULT 'default',
  messageStyle TEXT NOT NULL DEFAULT 'bubble',
  fontFamily TEXT NOT NULL DEFAULT 'sans',
  fontSize INTEGER NOT NULL DEFAULT 14,
  customFontUrl TEXT,
  language TEXT NOT NULL DEFAULT 'en',
  layoutMode TEXT NOT NULL DEFAULT 'auto',
  lastSeenPublic BOOLEAN NOT NULL DEFAULT false,
  onlinePublic BOOLEAN NOT NULL DEFAULT true,
  readReceipts BOOLEAN NOT NULL DEFAULT true,
  notifMessages BOOLEAN NOT NULL DEFAULT true,
  notifGroups BOOLEAN NOT NULL DEFAULT true,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS UserPreference_userId_key ON UserPreference(userId);

CREATE TABLE IF NOT EXISTS Subscription (
  id TEXT NOT NULL PRIMARY KEY,
  userId TEXT NOT NULL,
  plan TEXT NOT NULL,
  amount INTEGER NOT NULL,
  startAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expireAt DATETIME NOT NULL,
  isActive BOOLEAN NOT NULL DEFAULT true,
  source TEXT NOT NULL DEFAULT 'payment',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS Subscription_userId_isActive_idx ON Subscription(userId, isActive);

CREATE TABLE IF NOT EXISTS Referral (
  id TEXT NOT NULL PRIMARY KEY,
  referrerId TEXT NOT NULL,
  referredId TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  tierReached TEXT,
  rewardGranted BOOLEAN NOT NULL DEFAULT false,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  activatedAt DATETIME,
  FOREIGN KEY (referrerId) REFERENCES User(id),
  FOREIGN KEY (referredId) REFERENCES User(id)
);
CREATE UNIQUE INDEX IF NOT EXISTS Referral_referredId_key ON Referral(referredId);
CREATE INDEX IF NOT EXISTS Referral_referrerId_status_idx ON Referral(referrerId, status);

CREATE TABLE IF NOT EXISTS RedeemCode (
  id TEXT NOT NULL PRIMARY KEY,
  code TEXT NOT NULL,
  premiumMonths INTEGER NOT NULL,
  note TEXT NOT NULL DEFAULT '',
  count INTEGER NOT NULL DEFAULT 1,
  expiry DATETIME,
  isActive BOOLEAN NOT NULL DEFAULT true,
  createdById TEXT,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (createdById) REFERENCES User(id)
);
CREATE UNIQUE INDEX IF NOT EXISTS RedeemCode_code_key ON RedeemCode(code);
CREATE INDEX IF NOT EXISTS RedeemCode_isActive_idx ON RedeemCode(isActive);

CREATE TABLE IF NOT EXISTS RedeemUse (
  id TEXT NOT NULL PRIMARY KEY,
  codeId TEXT NOT NULL,
  userId TEXT NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (codeId) REFERENCES RedeemCode(id),
  FOREIGN KEY (userId) REFERENCES User(id)
);
CREATE UNIQUE INDEX IF NOT EXISTS RedeemUse_codeId_userId_key ON RedeemUse(codeId, userId);

CREATE TABLE IF NOT EXISTS DailyReward (
  id TEXT NOT NULL PRIMARY KEY,
  userId TEXT NOT NULL,
  dayNumber INTEGER NOT NULL,
  daysAwarded INTEGER NOT NULL,
  cycleStart DATETIME NOT NULL,
  claimedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES User(id)
);
CREATE INDEX IF NOT EXISTS DailyReward_userId_cycleStart_idx ON DailyReward(userId, cycleStart);

CREATE TABLE IF NOT EXISTS PaymentProof (
  id TEXT NOT NULL PRIMARY KEY,
  userId TEXT NOT NULL,
  plan TEXT NOT NULL,
  amount INTEGER NOT NULL,
  transactionId TEXT NOT NULL,
  utrNumber TEXT,
  screenshotUrl TEXT,
  notes TEXT,
  status TEXT NOT NULL DEFAULT 'pending',
  adminNote TEXT,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  reviewedAt DATETIME,
  FOREIGN KEY (userId) REFERENCES User(id)
);
CREATE INDEX IF NOT EXISTS PaymentProof_status_idx ON PaymentProof(status);

CREATE TABLE IF NOT EXISTS TalyRequest (
  id TEXT NOT NULL PRIMARY KEY,
  userId TEXT NOT NULL,
  chatId TEXT,
  request TEXT NOT NULL,
  reason TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'pending',
  adminNote TEXT,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  reviewedAt DATETIME,
  FOREIGN KEY (userId) REFERENCES User(id)
);
CREATE INDEX IF NOT EXISTS TalyRequest_status_idx ON TalyRequest(status);

CREATE TABLE IF NOT EXISTS AppSetting (
  id TEXT NOT NULL PRIMARY KEY,
  key TEXT NOT NULL,
  value TEXT NOT NULL,
  updatedAt DATETIME NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS AppSetting_key_key ON AppSetting(key);

CREATE TABLE IF NOT EXISTS ChatRequest (
  id TEXT NOT NULL PRIMARY KEY,
  senderId TEXT NOT NULL,
  receiverId TEXT NOT NULL,
  message TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'pending',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  decidedAt DATETIME,
  FOREIGN KEY (senderId) REFERENCES User(id),
  FOREIGN KEY (receiverId) REFERENCES User(id)
);
CREATE UNIQUE INDEX IF NOT EXISTS ChatRequest_senderId_receiverId_key ON ChatRequest(senderId, receiverId);
CREATE INDEX IF NOT EXISTS ChatRequest_receiverId_status_idx ON ChatRequest(receiverId, status);

CREATE TABLE IF NOT EXISTS GroupRequest (
  id TEXT NOT NULL PRIMARY KEY,
  groupId TEXT NOT NULL,
  senderId TEXT NOT NULL,
  message TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'pending',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  decidedAt DATETIME,
  FOREIGN KEY (groupId) REFERENCES Group(id) ON DELETE CASCADE,
  FOREIGN KEY (senderId) REFERENCES User(id)
);
CREATE UNIQUE INDEX IF NOT EXISTS GroupRequest_groupId_senderId_key ON GroupRequest(groupId, senderId);
CREATE INDEX IF NOT EXISTS GroupRequest_groupId_status_idx ON GroupRequest(groupId, status);

CREATE TABLE IF NOT EXISTS ReferralTask (
  id TEXT NOT NULL PRIMARY KEY,
  userId TEXT NOT NULL,
  tier TEXT NOT NULL,
  requiredCount INTEGER NOT NULL,
  windowDays INTEGER NOT NULL,
  rewardMonths INTEGER NOT NULL,
  selectedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completedAt DATETIME,
  expiresAt DATETIME NOT NULL,
  isActive BOOLEAN NOT NULL DEFAULT true,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ReferralTask_userId_isActive_idx ON ReferralTask(userId, isActive);

CREATE TABLE IF NOT EXISTS Story (
  id TEXT NOT NULL PRIMARY KEY,
  userId TEXT NOT NULL,
  type TEXT NOT NULL DEFAULT 'text',
  content TEXT NOT NULL DEFAULT '',
  bgColor TEXT NOT NULL DEFAULT '#10b981',
  textColor TEXT NOT NULL DEFAULT '#ffffff',
  caption TEXT,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expiresAt DATETIME NOT NULL,
  viewedBy TEXT NOT NULL DEFAULT '',
  isDeleted BOOLEAN NOT NULL DEFAULT false,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS Story_userId_createdAt_idx ON Story(userId, createdAt);
CREATE INDEX IF NOT EXISTS Story_expiresAt_idx ON Story(expiresAt);

CREATE TABLE IF NOT EXISTS StoryView (
  id TEXT NOT NULL PRIMARY KEY,
  storyId TEXT NOT NULL,
  userId TEXT NOT NULL,
  viewedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS StoryView_storyId_userId_key ON StoryView(storyId, userId);
CREATE INDEX IF NOT EXISTS StoryView_storyId_idx ON StoryView(storyId);

CREATE TABLE IF NOT EXISTS StoryHighlight (
  id TEXT NOT NULL PRIMARY KEY,
  userId TEXT NOT NULL,
  title TEXT NOT NULL DEFAULT 'Highlights',
  coverColor TEXT NOT NULL DEFAULT '#10b981',
  storyIds TEXT NOT NULL DEFAULT '',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS StoryHighlight_userId_idx ON StoryHighlight(userId);

CREATE TABLE IF NOT EXISTS ScheduledMessage (
  id TEXT NOT NULL PRIMARY KEY,
  senderId TEXT NOT NULL,
  conversationId TEXT NOT NULL,
  content TEXT NOT NULL,
  type TEXT NOT NULL DEFAULT 'text',
  mediaUrl TEXT,
  replyToId TEXT,
  scheduledFor DATETIME NOT NULL,
  isSent BOOLEAN NOT NULL DEFAULT false,
  isCancelled BOOLEAN NOT NULL DEFAULT false,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  sentAt DATETIME,
  FOREIGN KEY (senderId) REFERENCES User(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ScheduledMessage_isSent_scheduledFor_idx ON ScheduledMessage(isSent, scheduledFor);
CREATE INDEX IF NOT EXISTS ScheduledMessage_senderId_idx ON ScheduledMessage(senderId);

CREATE TABLE IF NOT EXISTS GroupAnnouncement (
  id TEXT NOT NULL PRIMARY KEY,
  groupId TEXT NOT NULL,
  authorId TEXT NOT NULL,
  content TEXT NOT NULL,
  isActive BOOLEAN NOT NULL DEFAULT true,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL,
  FOREIGN KEY (groupId) REFERENCES Group(id) ON DELETE CASCADE,
  FOREIGN KEY (authorId) REFERENCES User(id)
);
CREATE INDEX IF NOT EXISTS GroupAnnouncement_groupId_idx ON GroupAnnouncement(groupId);

CREATE TABLE IF NOT EXISTS PushSubscription (
  id TEXT NOT NULL PRIMARY KEY,
  userId TEXT NOT NULL,
  endpoint TEXT NOT NULL,
  p256dh TEXT,
  auth TEXT,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS LocationShare (
  id TEXT NOT NULL PRIMARY KEY,
  conversationId TEXT NOT NULL,
  userId TEXT NOT NULL,
  lat REAL NOT NULL,
  lng REAL NOT NULL,
  expiresAt DATETIME NOT NULL,
  isLive BOOLEAN NOT NULL DEFAULT true,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (conversationId) REFERENCES Conversation(id),
  FOREIGN KEY (userId) REFERENCES User(id)
);
`

export async function ensureDbSchema(db: PrismaClient) {
  if (initialized) return
  initialized = true
  
  // On Vercel, set DATABASE_URL to /tmp
  if (process.env.VERCEL) {
    const tmpDir = '/tmp/talychat-db'
    const tmpDb = path.join(tmpDir, 'custom.db')
    if (!existsSync(tmpDir)) {
      try { mkdirSync(tmpDir, { recursive: true }) } catch {}
    }
    process.env.DATABASE_URL = `file:${tmpDb}`
  }
  
  // Create tables using raw SQL
  try {
    const statements = SCHEMA_SQL.split(';').filter(s => s.trim())
    for (const stmt of statements) {
      if (stmt.trim()) {
        await db.$executeRawUnsafe(stmt + ';')
      }
    }
    console.log('[db-init] Schema created successfully')
  } catch (err) {
    console.error('[db-init] Error creating schema:', err)
  }
}
